config/routes.rb
Aria2web::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :downloads do
    get 'add',    on: :member
    get 'pause',  on: :member
    get 'resume', on: :member
    get 'stop',   on: :member
    get 'remove', on: :member
    get 'got',    on: :member
    get 'keep',   on: :member
    get 'stat',   on: :member, format: :json
  end

  root :to => 'downloads#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  
  belongs_to :parent,      class_name: "Category", foreign_key: "parent_id"
  has_many :subcategories, class_name: "Category"
  has_many :downloads
  
  def path join=" > "
    parent.nil? ? name : parent.path + join + name
  end
  
  def self.collection
    (all.map { |x| [x.path, x.id] }).sort
  end
end

app/models/download.rb
class Download < ActiveRecord::Base
  attr_accessible :uri, :category_id
  
  belongs_to :category
  belongs_to :user
  
  serialize :options
  serialize :files
  serialize :info
  
  validates :uri,      presence: true, uniqueness: true
  validates :user,     presence: true
  validates :category, presence: true
  
  scope :removed,     where(removed: true)
  scope :all_exist,   where(removed: false)
  scope :all_ordered, all_exist.order("status, completed_at DESC, created_at DESC")
  scope :to_add,      all_exist.where(status: :new)
  scope :to_check,    all_exist.where(status: [:added, :active])
  scope :to_clean,    all_exist.where(got:    true).order("keep, got, completed_at")
  scope :all_got,     all_exist.where(got: true, keep: false)
  scope :completed,   all_exist.where(status: :completed).order("completed_at DESC")
  
  before_create do
    self[:status]  = "new"
    self[:options] = {}
    self[:info]    = {}
    self[:files]   = []
  end
  
  def got?() got end
  def toggle_got
    self.got = !got
    save
  end
  
  def keep?() keep end
  def toggle_keep
    self.keep = !keep
    save
  end
  
  def removed?() removed end
  def remove
    self.removed = true
    save
  end
  
  def name
    if info.has_key? "name"
      info["name"]
    elsif not files.empty?
      File.basename files.first
    elsif uri =~ /^https?:/u or uri =~ /^ftp:/u
      File.basename(uri).split('?').first
    elsif uri =~ /^magnet:/u
      uri.split("&").select{ |part| part =~ /^dn=/u }.first[3..-1]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :downloads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to @category, :notice => "Successfully created category."
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category, :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url, :notice => "Successfully destroyed category."
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  
  def index
    DownloadManager.update_status_all
    respond_with(@downloads = Download.all_ordered)
  end

  def show
    @download = Download.find params[:id]
  end

  def new
    @download = Download.new
  end

  def create
    @download = Download.new params[:download]
    @download.user = current_user
    if @download.save
      redirect_to downloads_url, notice: "Successfully created download."
    else
      render action: 'new'
    end
  end
  
  def edit
    @download = Download.find params[:id]
  end

  def update
    @download = Download.find params[:id]
    if @download.update_attributes params[:download]
      redirect_to @download, notice: "Successfully updated download."
    else
      render action: 'edit'
    end
  end

  def destroy
    @download = Download.find params[:id]
    @download.destroy
    redirect_to downloads_url, notice: "Successfully destroyed download."
  end
  
  def stat
    status = DownloadManager.status Download.find(params[:id])
    render json: status
  end
  
  def add   () send_command params, message: "Added"   end
  def pause () send_command params, message: "Paused"  end
  def resume() send_command params, message: "Resumed" end
  def stop  () send_command params, message: "Stopped", command: :remove end
  
  def send_command params, options={}
    options[:command] ||= params[:action]
    resault = DownloadManager.send options[:command], Download.find(params[:id])
    
    respond_with(resault) do |format|
      format.html { redirect_to downloads_url, notice: resault }
    end
  end
  
  def got  () send_download_command params, :toggle_got,  message: "got toggled"  end
  def keep () send_download_command params, :toggle_keep, message: "keep toggled" end
  
  def send_download_command params, command, options={}
    command           ||= params[:action]
    options[:message] ||= "#{:command} done"
    options[:error]   ||= "Error"
    
    resault = Download.find(params[:id]).send command

    respond_with(resault) do |format|
      format.html { redirect_to downloads_url, notice: (resault ? options[:message] : options[:error]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
  def link_for action, label=nil
    label ||= action
    link_to label, url_for(controller: :downloads, action: action, only_path: true, id: @download.id)
  end
  
  def links_for download
    @download = download
    
    case download.status
    when "new"
      link_for(:add, :start)
    when "active"
      [link_for(:pause), link_for(:stop)]
    when "waiting"
      [link_for(:pause), link_for(:stop)]
    when "paused"
      [link_for(:resume), link_for(:add, :restart)]
    when "stopped"
      link_for(:remove)
    when "error"
      link_for(:add, :retry)
    when "complete"
      [download.got?  ? link_for(:got,  "remove got mark")  : link_for(:got, "mark as got"),
       download.keep? ? link_for(:keep, "remove keep mark") : link_for(:keep, "mark for keep")]
    else
      []
    end
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/categories/_form.html.erb
<%= semantic_form_for @category do |f| %>
  <%= f.inputs %>
  <%= f.buttons %>
<% end %>

app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/categories/index.html.erb
<% title "Categories" %>

<table>
  <tr>
    <th>Name</th>
    <th>Parent</th>
  </tr>
  <% for category in @categories %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.parent_id %></td>
      <td><%= link_to "Show", category %></td>
      <td><%= link_to "Edit", edit_category_path(category) %></td>
      <td><%= link_to "Destroy", category, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Category", new_category_path %></p>

app/views/categories/new.html.erb
<% title "New Category" %>

<%= render 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

app/views/categories/show.html.erb
<% title "Category" %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<p>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/downloads/_form.html.erb
<%= semantic_form_for @download do |f| -%>
  <%= f.inputs do -%>
    <%= f.input :uri %>
    <%= f.input :category, collection: Category.collection %>
  <% end -%>
  <%= f.buttons %>
<% end -%>

app/views/downloads/edit.html.erb
<% title "Edit Download" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @download %> |
  <%= link_to "View All", downloads_path %>
</p>

app/views/downloads/index.html.erb
<% title "Downloads" %>

<table>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Gid</th>
    <th>Status</th>
    <th>Completed At</th>
    <th>Error</th>
  </tr>
  <% for download in @downloads %>
    <tr>
      <td><%= download.id %></td>
      <td><%= download.name %></td>
      <td><%= download.gid %></td>
      <td><%= download.status %></td>
      <td><%= download.completed_at %></td>
      <td><%= download.error %></td>
      <td>
      <% [*links_for(download)].each do |link| -%>
        <%= link %>
      <% end -%>
      </td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Download", new_download_path %></p>

app/views/downloads/new.html.erb
<% title "New Download" %>

<%= render 'form' %>

<p><%= link_to "Back to List", downloads_path %></p>

app/views/downloads/show.html.erb
<% title "Download" %>

<p>
  <strong>Uri:</strong>
  <%= @download.uri %>
</p>
<p>
  <strong>Gid:</strong>
  <%= @download.gid %>
</p>
<p>
  <strong>Status:</strong>
  <%= @download.status %>
</p>
<p>
  <strong>Options:</strong>
  <%= @download.options %>
</p>
<p>
  <strong>Completed At:</strong>
  <%= @download.completed_at %>
</p>
<p>
  <strong>Error:</strong>
  <%= @download.error %>
</p>
<p>
  <strong>Info:</strong>
  <%= @download.info %>
</p>

<p>
  <%= link_to "Edit", edit_download_path(@download) %> |
  <%= link_to "Destroy", @download, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", downloads_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>